import ApiImageUri from './ApiImageUri';
import ApiRelatedUri from './ApiRelatedUri';
import ApiPurchaseUri from './ApiPurchaseUri';
import ApiPrice from './ApiPrice';
import ApiLegality from './ApiLegality';

type ApiCard = {
  //core properties
  id: string;
  arena_id: number;
  lang: string;
  mtgo_id: number;
  mtgo_foil_id: number;
  multiverse_ids: number[];
  tcgplayer_id: number;
  tcgplayer_etched_id: number;
  cardmarket_id: number;
  object: string;
  layout: string;
  oracle_id: string;
  prints_search_uri: string;
  rulings_uri: string;
  scryfall_uri: string;
  uri: string;

  //gameplay properties
  all_parts: {
    object: string;
    id: string;
    component: string;
    name: string;
    type_line: string;
    uri: string;
  }[];
  card_faces: {
    artist: string;
    artist_id: string;
    cmc: number;
    color_indicator: string[];
    colors: string[];
    defense: string;
    flavor_text: string;
    illustration_id: string;
    image_uris: ApiImageUri;
    layout: string;
    loyalty: string;
    mana_cost: string;
    name: string;
    object: string;
    oracle_id: string;
    oracle_text: string;
    power: string;
    printed_name: string;
    printed_text: string;
    printed_type_line: string;
    toughness: string;
    type_line: string;
    watermark: string;
  };
  cmc: number;
  color_identity: string[];
  color_indicator: string[];
  colors: string[];
  edhrec_rank: number;
  hand_modifier: string;
  keywords: string[];
  legalities: ApiLegality;
  life_modifier: string;
  loyalty: string;
  mana_cost: string;
  name: string;
  oracle_text: string;
  penny_rank: number;
  power: string;
  produced_mana: string[];
  reserved: boolean;
  toughness: string;
  type_line: string;

  //print properties
  artist: string;
  artist_ids: string[];
  attraction_lights: string[];
  booster: boolean;
  border_color: string;
  card_back_id: string;
  collector_number: string;
  content_warning: boolean;
  digital: boolean;
  finishes: string[];
  flavor_name: string;
  flavor_text: string;
  frame_effects: string[];
  frame: string;
  full_art: boolean;
  games: string[];
  highres_image: boolean;
  illustration_id: string;
  image_status: string;
  image_uris: ApiImageUri;
  oversized: boolean;
  prices: ApiPrice;
  printed_name: string;
  printed_text: string;
  printed_type_line: string;
  promo: boolean;
  promo_types: string[];
  purchase_uris: ApiPurchaseUri;
  rarity: string;
  related_uris: ApiRelatedUri;
  released_at: string;
  reprint: boolean;
  scryfall_set_uri: string;
  set_name: string;
  set_search_uri: string;
  set_type: string;
  set_uri: string;
  set: string;
  set_id: string;
  story_spotlight: boolean;
  textless: boolean;
  variation: boolean;
  variation_of: string;
  security_stamp: string;
  watermark: string;
  preview: {
    previewed_at: Date;
    source_uri: string;
    source: string;
  };
};

export default ApiCard;
